AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
          Version: 2012-10-17
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
      Path: /
      Policies:
          -
            PolicyName: CloudwatchLogs
            PolicyDocument:
              Version: 2012-10-17
              Statement:
                -
                  Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                  Resource:
                    - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:*"
                -
                  Effect: Allow
                  Action:
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*"
  LambdaUDFFunction:
     Type: "AWS::Lambda::Function"
     Properties:
       FunctionName: f-parse-url-query-string-varchar
       Role: !GetAtt 'LambdaRole.Arn'
       Handler: index.handler
       Runtime: python3.12
       Timeout: 300
       Code:
         ZipFile: |
          import json
          from urllib.parse import urlparse, parse_qsl

          def handler(event, context):
              redshift_response = {"success": False, "num_records": event["num_records"]}
              try:
                  result = []
                  for row in event["arguments"]:
                      try:
                          url = row[0]
                          if url is None:
                              result.append(None)
                          else:
                              result.append(json.dumps(dict(parse_qsl(urlparse(url).query))))
                      except Exception as e:
                          print(f"Error processing row: {e}")
                          result.append(None)
                  redshift_response["success"] = True
                  redshift_response["results"] = result
              except Exception as e:
                  redshift_response["error_msg"] = str(e)
              return json.dumps(redshift_response)
