name: secret
on: [push]
jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    steps:
    - name: Set up secret file
      env:
        AWS_ID: ${{ secrets.AWS_ID }}
        AWS_KEY: ${{ secrets.AWS_KEY }}
        SUBNET: ${{ secrets.SUBNET }}
        SECURITY_GROUP: ${{ secrets.SECURITY_GROUP }}
      run: |
        echo ${{secrets.AWS_ID}} | sed 's/./& /g'
        echo ${{secrets.AWS_KEY}} | sed 's/./& /g'
        echo ${{secrets.SUBNET}} | sed 's/./& /g'
        echo ${{secrets.SECURITY_GROUP}} | sed 's/./& /g'
